import type { AuditResult, Tier } from '@diskwise/core/types';
import { TIER_NAMES } from '@diskwise/core/types';
import { formatBytes } from './format';

const TIERS: Tier[] = [0, 1, 2, 3];

function cell(value: string): string {
  return value.replace(/\|/g, '\\|').replace(/\s*\n\s*/g, ' ');
}

export function auditMarkdown(audit: AuditResult, opts: { redact?: boolean } = {}): string {
  const lines: string[] = [];
  lines.push('# DiskWise report');
  lines.push('');
  const when = audit.macosVersion
    ? `${audit.generatedAt} · macOS ${audit.macosVersion}`
    : audit.generatedAt;
  lines.push(`Generated ${when}`);
  lines.push('');
  lines.push(`Reclaimable: ${formatBytes(audit.totals.reclaimable)}`);
  lines.push('');

  for (const tier of TIERS) {
    const findings = audit.findings.filter((finding) => finding.tier === tier);
    if (findings.length === 0) continue;
    lines.push(`## ${TIER_NAMES[tier]}`);
    lines.push('');
    lines.push('| Item | Size | Why |');
    lines.push('| --- | ---: | --- |');
    for (const finding of findings) {
      lines.push(
        `| ${cell(finding.title)} | ${formatBytes(finding.totals.allocated)} | ${cell(
          finding.rationale,
        )} |`,
      );
    }
    lines.push('');
  }

  lines.push(`_Generated by DiskWise. ${audit.findings.length} items._`);
  lines.push('');

  const text = lines.join('\n');
  return opts.redact ? text.replace(/\/Users\/[^/\s]+/g, '~') : text;
}

export function downloadMarkdown(filename: string, markdown: string): void {
  const blob = new Blob([markdown], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = filename;
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  URL.revokeObjectURL(url);
}
