import type { AuditResult, Finding, Tier } from '@macsweep/core';
import { formatBytes } from './format-bytes';

const TIERS: Tier[] = [0, 1, 2, 3];

const TIER_TITLES: Record<Tier, string> = {
  0: 'Tier 0 · Regenerates',
  1: 'Tier 1 · Re-download',
  2: 'Tier 2 · Your data',
  3: 'Tier 3 · Protected (report only)',
};

const MAX_MATCHES = 10;

function cell(value: string): string {
  return value.replace(/\r?\n/g, ' ').replace(/\|/g, '\\|');
}

function itemTitle(finding: Finding): string {
  const badges: string[] = [];
  if (finding.needsRoot) badges.push('[needs root]');
  if (finding.permanentOnly) badges.push('[permanent only]');
  return badges.length > 0 ? `${finding.title} ${badges.join(' ')}` : finding.title;
}

export function formatMarkdown(result: AuditResult, opts: { version?: string } = {}): string {
  const lines: string[] = [];

  lines.push('# macsweep disk report');
  lines.push('');
  lines.push(
    result.macosVersion
      ? `Generated ${result.generatedAt} · macOS ${result.macosVersion}`
      : `Generated ${result.generatedAt}`,
  );
  lines.push('');

  if (result.disk) {
    const d = result.disk;
    lines.push('| Container | Used | Free |');
    lines.push('| --- | --- | --- |');
    lines.push(`| ${cell(d.volumeName)} | ${formatBytes(d.containerUsed)} | ${formatBytes(d.containerFree)} |`);
    lines.push('');
  }

  if (result.permissions?.fullDiskAccess === 'limited') {
    const hint = result.permissions.hint ? ` ${result.permissions.hint}` : '';
    lines.push(`> Full Disk Access: limited.${hint}`);
    lines.push('');
  }

  lines.push('## Summary');
  lines.push('');
  lines.push(`Reclaimable: **${formatBytes(result.totals.reclaimable)}**`);
  lines.push('');
  for (const tier of TIERS) {
    lines.push(`- ${TIER_TITLES[tier]}: ${formatBytes(result.totals.byTier[tier])}`);
  }
  lines.push('');

  for (const tier of TIERS) {
    const findings = result.findings.filter((f) => f.tier === tier);
    if (findings.length === 0) continue;

    lines.push(`## ${TIER_TITLES[tier]}`);
    lines.push('');
    lines.push('| Item | Size | Why it is safe | Restore cost |');
    lines.push('| --- | --- | --- | --- |');
    for (const finding of findings) {
      lines.push(
        `| ${cell(itemTitle(finding))} | ${formatBytes(finding.totals.allocated)} | ${cell(finding.rationale)} | ${cell(finding.regeneration)} |`,
      );
    }
    lines.push('');

    for (const finding of findings) {
      if (finding.matches.length === 0) continue;
      lines.push('<details><summary>Items</summary>');
      lines.push('');
      for (const match of finding.matches.slice(0, MAX_MATCHES)) {
        lines.push(`- \`${match.detail}\` - ${formatBytes(match.bytesAllocated)}`);
      }
      if (finding.matches.length > MAX_MATCHES) {
        lines.push(`- … and ${finding.matches.length - MAX_MATCHES} more`);
      }
      lines.push('');
      lines.push('</details>');
      lines.push('');
    }
  }

  lines.push('## Traps');
  lines.push('');
  for (const trap of result.traps) {
    lines.push(
      `- \`${trap.path}\` looks like ${formatBytes(trap.apparent)} but uses ${formatBytes(trap.allocated)} - ${trap.note}`,
    );
  }
  lines.push('');

  const unreadable = result.unreadable.length;
  lines.push('## Unreadable');
  lines.push('');
  lines.push(`${unreadable} ${unreadable === 1 ? 'path' : 'paths'}`);
  lines.push('');

  lines.push(`_Generated by macsweep${opts.version ? ` ${opts.version}` : ''}. Nothing was deleted._`);

  return `${lines.join('\n')}\n`;
}
